/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 用户注册。校验 email 唯一、密码最小 8 位后写入 users 表（bcrypt 哈希）。
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token
         * @description 登录获取 token。接收 OAuth2PasswordRequestForm（username=email, password），校验 bcrypt 后签发 access + refresh token。
         */
        post: operations["token_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 获取当前登录用户信息。需携带 Bearer access token。
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description 使用 refresh token 换取新的 access token（并轮换 refresh token）。refresh token 过期或无效返回 401。
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查。依赖（DB/Redis）可达返回 ok，否则 degraded（仍 200）。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description 根路径。
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prompts
         * @description 分页列出所有 Prompt，支持按名称模糊搜索。
         */
        get: operations["list_prompts_api_v1_prompts_get"];
        put?: never;
        /**
         * Create Prompt
         * @description 创建新 Prompt 及其首个版本。
         */
        post: operations["create_prompt_api_v1_prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{prompt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prompt
         * @description 获取指定 Prompt 的详情（含当前版本）。
         */
        get: operations["get_prompt_api_v1_prompts__prompt_id__get"];
        /**
         * Update Prompt
         * @description 更新 Prompt 元数据（名称、描述），不产生新版本。
         */
        put: operations["update_prompt_api_v1_prompts__prompt_id__put"];
        post?: never;
        /**
         * Delete Prompt
         * @description 删除指定 Prompt 及其所有版本。
         */
        delete: operations["delete_prompt_api_v1_prompts__prompt_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{prompt_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description 列出指定 Prompt 的全部历史版本。
         */
        get: operations["list_versions_api_v1_prompts__prompt_id__versions_get"];
        put?: never;
        /**
         * Create Version
         * @description 为指定 Prompt 创建新版本。
         */
        post: operations["create_version_api_v1_prompts__prompt_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{prompt_id}/versions/{version_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback Version
         * @description 回滚到指定版本，将其设为当前版本。
         */
        post: operations["rollback_version_api_v1_prompts__prompt_id__versions__version_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{prompt_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff Versions
         * @description 对比两个版本号之间的内容差异。
         */
        get: operations["diff_versions_api_v1_prompts__prompt_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description 分页列出所有 Agent。
         */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        /**
         * Create Agent
         * @description 创建新 Agent。
         */
        post: operations["create_agent_api_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description 获取指定 Agent 的详情。
         */
        get: operations["get_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Agent
         * @description 执行指定 Agent，返回执行结果与 token 用量。
         */
        post: operations["execute_agent_api_v1_agents__agent_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflows
         * @description 分页列出所有工作流。
         */
        get: operations["list_workflows_api_v1_workflows_get"];
        put?: never;
        /**
         * Create Workflow
         * @description 创建新工作流（DAG 编排）。
         */
        post: operations["create_workflow_api_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Workflow
         * @description 执行指定工作流，返回执行追踪。
         */
        post: operations["execute_workflow_api_v1_workflows__workflow_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Kbs
         * @description 分页列出所有知识库。
         */
        get: operations["list_kbs_api_v1_knowledge_bases_get"];
        put?: never;
        /**
         * Create Kb
         * @description 创建新知识库。
         */
        post: operations["create_kb_api_v1_knowledge_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{kb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kb
         * @description 获取指定知识库的详情。
         */
        get: operations["get_kb_api_v1_knowledge_bases__kb_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{kb_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description 上传文档到指定知识库，进入异步分块与向量化队列。
         */
        post: operations["upload_document_api_v1_knowledge_bases__kb_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{kb_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Kb
         * @description 对指定知识库进行语义检索，返回相似文本块。
         */
        post: operations["search_kb_api_v1_knowledge_bases__kb_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{kb_id}/rag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rag Query
         * @description 对指定知识库执行 RAG 问答，返回生成结果。
         */
        post: operations["rag_query_api_v1_knowledge_bases__kb_id__rag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description 分页列出模型配置，可按启用状态过滤。
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /**
         * Create Model
         * @description 创建新模型配置。
         */
        post: operations["create_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model
         * @description 按别名获取模型配置详情。
         */
        get: operations["get_model_api_v1_models__alias__get"];
        /**
         * Update Model
         * @description 更新指定别名的模型配置。
         */
        put: operations["update_model_api_v1_models__alias__put"];
        post?: never;
        /**
         * Delete Model
         * @description 删除指定别名的模型配置。
         */
        delete: operations["delete_model_api_v1_models__alias__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{alias}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description 调用指定模型进行聊天补全。
         */
        post: operations["chat_api_v1_models__alias__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description 分页列出对话记录，可按用户过滤。
         */
        get: operations["list_conversations_api_v1_analytics_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 获取指定对话记录详情。
         */
        get: operations["get_conversation_api_v1_analytics_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description 获取仪表盘聚合指标（近 N 天）。
         */
        get: operations["dashboard_api_v1_analytics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evals
         * @description 分页列出评估任务。
         */
        get: operations["list_evals_api_v1_evals_get"];
        put?: never;
        /**
         * Create Eval
         * @description 创建评估任务。
         */
        post: operations["create_eval_api_v1_evals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval
         * @description 获取指定评估任务详情。
         */
        get: operations["get_eval_api_v1_evals__eval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals/{eval_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Eval
         * @description 同步执行 eval。predict_fn 为 None 时用 case.expected 自比对。
         */
        post: operations["run_eval_api_v1_evals__eval_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 统一错误响应体（遵循 errors.spec.md§2）。 */
        Error: {
            /** @description 错误码（snake_case）：not_found / validation_error / token_invalid / token_expired / permission_denied / conflict / rate_limited / llm_error / internal_error。 */
            error: string;
            /** @description 面向用户的可读错误信息。 */
            message: string;
            /** @description 附加详情（可为字符串、数组或对象）。detail 为 null 时省略该字段。 */
            detail?: unknown;
        };
        /**
         * UserCreate
         * @description 注册入参。
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Password
             * Format: password
             * @description 明文密码，落库前 bcrypt 哈希
             */
            password: string;
        };
        /**
         * UserOut
         * @description 用户对外视图。
         */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Role
             * @description 由 users.is_admin 派生（is_admin=true → admin）。
             * @enum {string}
             */
            role: "admin" | "user";
        };
        /**
         * Token
         * @description 登录 / 刷新返回的 token 包。
         */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description access token 有效秒数
             */
            expires_in: number;
        };
        /**
         * RefreshRequest
         * @description 刷新请求体。
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Body_token_api_v1_auth_token_post
         * @description OAuth2PasswordRequestForm（application/x-www-form-urlencoded）。
         */
        Body_token_api_v1_auth_token_post: {
            /**
             * Username
             * @description email
             */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * AgentCreate
         * @description 创建 Agent 入参。
         */
        AgentCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /**
             * Model Alias
             * @default default
             */
            model_alias: string;
            /** Tools */
            tools?: components["schemas"]["ToolDef"][];
            /**
             * Max Turns
             * @default 10
             */
            max_turns: number;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
        };
        /**
         * AgentNode
         * @description 工作流节点定义。
         */
        AgentNode: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id?: string | null;
            /** Name */
            name: string;
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
            /**
             * Is Entry
             * @default false
             */
            is_entry: boolean;
            /**
             * Is Exit
             * @default false
             */
            is_exit: boolean;
        };
        /** AgentOut */
        AgentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Model Alias */
            model_alias: string;
            /** Tools */
            tools: {
                [key: string]: unknown;
            }[];
            /** Max Turns */
            max_turns: number;
            /** Temperature */
            temperature: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Body_upload_document_api_v1_knowledge_bases__kb_id__documents_post */
        Body_upload_document_api_v1_knowledge_bases__kb_id__documents_post: {
            /** Title */
            title: string;
            /** File */
            file: string;
        };
        /**
         * ChatMessage
         * @description 对话消息。
         */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * ChatRequest
         * @description 聊天请求。
         */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Temperature */
            temperature?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** @default direct */
            strategy: components["schemas"]["RoutingStrategy"];
        };
        /**
         * ChatResponse
         * @description 聊天响应。
         */
        ChatResponse: {
            /** Content */
            content: string;
            /** Model */
            model: string;
            /** Alias */
            alias: string;
            /** Usage */
            usage?: {
                [key: string]: unknown;
            };
            /**
             * Cost
             * @default 0
             */
            cost: string;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /** Model Alias */
            model_alias?: string | null;
            /** Title */
            title?: string | null;
            /** Total Tokens */
            total_tokens: number;
            /** Total Cost */
            total_cost: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages?: components["schemas"]["MessageOut"][];
        };
        /**
         * DashboardMetrics
         * @description 仪表盘指标。按时间维度聚合。
         */
        DashboardMetrics: {
            /**
             * Total Conversations
             * @default 0
             */
            total_conversations: number;
            /**
             * Total Messages
             * @default 0
             */
            total_messages: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: string;
            /**
             * Avg Messages Per Conversation
             * @default 0
             */
            avg_messages_per_conversation: number;
            /**
             * Avg Latency Ms
             * @default 0
             */
            avg_latency_ms: number;
            /** Active Models */
            active_models?: {
                [key: string]: unknown;
            }[];
            /** Conversations Last 7D */
            conversations_last_7d?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DiffResult
         * @description 版本 diff 结果。
         */
        DiffResult: {
            /** From Version */
            from_version: number;
            /** To Version */
            to_version: number;
            /** Added Lines */
            added_lines?: string[];
            /** Removed Lines */
            removed_lines?: string[];
            /** Unified Diff */
            unified_diff?: string[];
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /** Title */
            title: string;
            /** Source Uri */
            source_uri?: string | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Chunk Count */
            chunk_count: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EvalCaseInput
         * @description 评估用例入参。
         */
        EvalCaseInput: {
            /** Name */
            name?: string | null;
            /** Input */
            input: string;
            /** Expected */
            expected?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * EvalRuleInput
         * @description 评估规则入参。
         */
        EvalRuleInput: {
            /** Name */
            name: string;
            /** @default exact */
            judge_type: components["schemas"]["JudgeType"];
            /** Expected */
            expected?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /**
         * EvalRunCreate
         * @description 创建 eval 入参。
         */
        EvalRunCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Rules */
            rules?: components["schemas"]["EvalRuleInput"][];
            /** Cases */
            cases?: components["schemas"]["EvalCaseInput"][];
            /** @default exact */
            judge_type: components["schemas"]["JudgeType"];
        };
        /** EvalRunOut */
        EvalRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Rules */
            rules: {
                [key: string]: unknown;
            }[];
            /** Cases */
            cases: {
                [key: string]: unknown;
            }[];
            /** Judge Type */
            judge_type: string;
            /** Status */
            status: string;
            /** Results */
            results?: {
                [key: string]: unknown;
            }[] | null;
            /** Pass Count */
            pass_count: number;
            /** Fail Count */
            fail_count: number;
            /** Score */
            score?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ExecuteRequest
         * @description 执行 Agent 请求体。
         */
        ExecuteRequest: {
            /** Input */
            input: string;
            /** Max Turns */
            max_turns?: number | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExecutionResult
         * @description Agent / Workflow 执行结果。
         */
        ExecutionResult: {
            /** Agent Id */
            agent_id?: string | null;
            /** Workflow Id */
            workflow_id?: string | null;
            /** Final Answer */
            final_answer: string;
            /** Traces */
            traces?: components["schemas"]["ExecutionTrace"][];
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
        };
        /**
         * ExecutionTrace
         * @description 单步执行追踪。
         */
        ExecutionTrace: {
            /** Turn */
            turn: number;
            /** Thought */
            thought: string;
            /** Action */
            action?: string | null;
            /** Observation */
            observation?: string | null;
            /**
             * Tokens
             * @default 0
             */
            tokens: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JudgeType
         * @description 判官类型。
         * @enum {string}
         */
        JudgeType: "exact" | "contains" | "llm" | "semantic";
        /**
         * KnowledgeBaseCreate
         * @description 创建知识库入参。
         */
        KnowledgeBaseCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Embedding Model
             * @default text-embedding-3-small
             */
            embedding_model: string;
            /**
             * Chunk Size
             * @default 800
             */
            chunk_size: number;
            /**
             * Chunk Overlap
             * @default 100
             */
            chunk_overlap: number;
        };
        /** KnowledgeBaseOut */
        KnowledgeBaseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Embedding Model */
            embedding_model: string;
            /** Chunk Size */
            chunk_size: number;
            /** Chunk Overlap */
            chunk_overlap: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model Alias */
            model_alias?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ModelConfigCreate
         * @description 创建模型配置入参。
         */
        ModelConfigCreate: {
            /** Alias */
            alias: string;
            /** @default openai */
            provider: components["schemas"]["ModelProvider"];
            /** Model Name */
            model_name: string;
            /** Api Base */
            api_base?: string | null;
            /** Api Key Env */
            api_key_env?: string | null;
            /**
             * Max Tokens
             * @default 4096
             */
            max_tokens: number;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Cost Per 1K Input
             * @default 0
             */
            cost_per_1k_input: number | string;
            /**
             * Cost Per 1K Output
             * @default 0
             */
            cost_per_1k_output: number | string;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ModelConfigOut */
        ModelConfigOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Alias */
            alias: string;
            /** Provider */
            provider: string;
            /** Model Name */
            model_name: string;
            /** Api Base */
            api_base?: string | null;
            /** Api Key Env */
            api_key_env?: string | null;
            /** Max Tokens */
            max_tokens: number;
            /** Temperature */
            temperature: number;
            /** Cost Per 1K Input */
            cost_per_1k_input: string;
            /** Cost Per 1K Output */
            cost_per_1k_output: string;
            /** Is Active */
            is_active: boolean;
            /** Priority */
            priority: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ModelConfigUpdate
         * @description 更新模型配置入参。
         */
        ModelConfigUpdate: {
            /** Model Name */
            model_name?: string | null;
            /** Api Base */
            api_base?: string | null;
            /** Api Key Env */
            api_key_env?: string | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Cost Per 1K Input */
            cost_per_1k_input?: number | string | null;
            /** Cost Per 1K Output */
            cost_per_1k_output?: number | string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Priority */
            priority?: number | null;
        };
        /**
         * ModelProvider
         * @description 模型供应商。
         * @enum {string}
         */
        ModelProvider: "openai" | "anthropic" | "local" | "azure_openai" | "custom";
        /**
         * PromptCreate
         * @description 创建 Prompt 入参（含初始版本内容）。
         */
        PromptCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Content */
            content: string;
            /** Variables */
            variables?: string[];
        };
        /** PromptOut */
        PromptOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Current Version Id */
            current_version_id?: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions?: components["schemas"]["PromptVersionOut"][];
        };
        /**
         * PromptUpdate
         * @description 更新 Prompt 元信息。
         */
        PromptUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * PromptVersionCreate
         * @description 新增版本入参。
         */
        PromptVersionCreate: {
            /** Content */
            content: string;
            /** Variables */
            variables?: string[];
            /** Change Note */
            change_note?: string | null;
        };
        /** PromptVersionOut */
        PromptVersionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Prompt Id
             * Format: uuid
             */
            prompt_id: string;
            /** Version Num */
            version_num: number;
            /** Content */
            content: string;
            /** Variables */
            variables: string[];
            /** Change Note */
            change_note?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RAGQuery
         * @description RAG 查询请求（检索 + LLM 生成）。
         */
        RAGQuery: {
            /** Question */
            question: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /**
         * RoutingStrategy
         * @description 路由策略。
         * @enum {string}
         */
        RoutingStrategy: "direct" | "round_robin" | "least_cost" | "latency";
        /**
         * SearchQuery
         * @description 向量检索请求。
         */
        SearchQuery: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /**
             * Score Threshold
             * @default 0
             */
            score_threshold: number;
        };
        /**
         * SearchResult
         * @description 单条检索结果。
         */
        SearchResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ToolDef
         * @description 工具定义。
         */
        ToolDef: {
            /** Name */
            name: string;
            /** @default custom */
            type: components["schemas"]["ToolType"];
            /** Description */
            description?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /**
         * ToolType
         * @description 工具类型。
         * @enum {string}
         */
        ToolType: "search" | "calculator" | "http" | "code" | "rag" | "custom";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowDef
         * @description 创建工作流入参。
         */
        WorkflowDef: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Nodes */
            nodes?: components["schemas"]["AgentNode"][];
            /** Edges */
            edges?: components["schemas"]["WorkflowEdge"][];
        };
        /**
         * WorkflowEdge
         * @description 工作流边。
         */
        WorkflowEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Condition */
            condition?: string | null;
        };
        /** WorkflowOut */
        WorkflowOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Nodes */
            nodes: {
                [key: string]: unknown;
            }[];
            /** Edges */
            edges: {
                [key: string]: unknown;
            }[];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: {
        /** @description 请求格式或语义错误（400 Bad Request）。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证或凭据无效（401 Unauthorized）。error 为 token_invalid 或 token_expired。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 无权限访问该资源（403 Forbidden）。error 为 permission_denied。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在（404 Not Found）。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源冲突，如 email 或唯一字段重复（409 Conflict）。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求频率超限（429 Too Many Requests）。error 为 rate_limited。 */
        TooManyRequests: {
            headers: {
                /** @description 窗口内允许的请求总数。 */
                "X-RateLimit-Limit"?: number;
                /** @description 窗口内剩余请求数。 */
                "X-RateLimit-Remaining"?: number;
                /** @description 窗口重置时间（Unix 时间戳）。 */
                "X-RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求参数校验失败（422 Validation Error），统一错误格式。 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 上游 LLM 服务调用失败（502 Bad Gateway）。error 为 llm_error。 */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务器内部错误（500 Internal Server Error）。 */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description 注册成功，返回新建用户。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    token_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_token_api_v1_auth_token_post"];
            };
        };
        responses: {
            /** @description 登录成功，返回 token 包。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户信息。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 刷新成功，返回新 token 包。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        version: string;
                        checks: {
                            /** @enum {string} */
                            database: "ok" | "down";
                            /** @enum {string} */
                            redis: "ok" | "down";
                        };
                    };
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_prompts_api_v1_prompts_get: {
        parameters: {
            query?: {
                /** @description 名称模糊搜索 */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    create_prompt_api_v1_prompts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    get_prompt_api_v1_prompts__prompt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    update_prompt_api_v1_prompts__prompt_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    delete_prompt_api_v1_prompts__prompt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_versions_api_v1_prompts__prompt_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionOut"][];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    create_version_api_v1_prompts__prompt_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    rollback_version_api_v1_prompts__prompt_id__versions__version_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    diff_versions_api_v1_prompts__prompt_id__diff_get: {
        parameters: {
            query: {
                /** @description 起始版本号 */
                from: number;
                /** @description 目标版本号 */
                to: number;
            };
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    create_agent_api_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    get_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    execute_agent_api_v1_agents__agent_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_workflows_api_v1_workflows_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    create_workflow_api_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDef"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    execute_workflow_api_v1_workflows__workflow_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_kbs_api_v1_knowledge_bases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    create_kb_api_v1_knowledge_bases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    get_kb_api_v1_knowledge_bases__kb_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    upload_document_api_v1_knowledge_bases__kb_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_knowledge_bases__kb_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    search_kb_api_v1_knowledge_bases__kb_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    rag_query_api_v1_knowledge_bases__kb_id__rag_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RAGQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: {
                active_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    create_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    get_model_api_v1_models__alias__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    update_model_api_v1_models__alias__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    delete_model_api_v1_models__alias__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    chat_api_v1_models__alias__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_conversations_api_v1_analytics_conversations_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    get_conversation_api_v1_analytics_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    dashboard_api_v1_analytics_dashboard_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    list_evals_api_v1_evals_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    create_eval_api_v1_evals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    get_eval_api_v1_evals__eval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    run_eval_api_v1_evals__eval_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
